accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


# from django.contrib.auth.models import user
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)
from django.urls import path


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("tasks/mine/", TaskListView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.urls import include
from django.views.generic.base import RedirectView
from tasks.views import TaskListView


urlpatterns = [
    path("tasks/mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
    # from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.

def signup(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()  # user=form.save
            login(request, user)
            return redirect("home")

    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.shortcuts import redirect
from projects.models import Project
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    # context_object_name = project_dv

    # def get_queryset(self):
    #     return Task.objects.filter.all

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

    #     tasks = []
    #     if self.request.user.is_authenticated:
    #         for tasks in self.request.tasks.project.all():
    #             tasks.append(ProjectDetailView)
    #             #tasks.append(tasks.task.name)

    #     context["tasks_in_project_detail"] = tasks
    #     return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]
    success_url = reverse_lazy("project_detailview")
    # handle form submission

    def form_valid(self, form):
        item = form.save(commit=False)
        # item.members.set(self.request.user)
        item.members = self.request.user
        item.save()
        return redirect("show_project")

tasks/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from tasks.models import Task

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    # Create a view that will show a form to create an instance of the Task model for all properties except the is_completed field
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]
    success_url = reverse_lazy("task_detail")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.member = self.request.user
        item.save()
        return redirect(
            "projects/detail.html"
        )  # When the view successfully handles the form submission, have it redirect to the detail page of the task's project


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def form_valid(self, form):
        form.instance.task.all = self.request.user
        return super().form_valid(form)

    # This feature allows a logged in person to see the tasks that are assigned to them.
    # Create a list view for the Task model with the objects filtered so that the person only sees the tasks assigned to them by filtering with the assignee equal to the currently logged in user#


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    # Create an update view for the Task model that only is concerned with the is_completed field
    fields = ["is_comlpeted"]
    success_url = reverse_lazy("show_my_tasks")
    # http://localhost:8000/tasks/mine/

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main tag is in the base.html file -->
    <div>
        <br>
        <h1>Create a new project</h1>
        <p>
            <a href="http://localhost:8000/projects/create.html"> Create a new project </a>
            <!--need to link this up and check the correct url -->
        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <label> Name: </label>
                <input type="text" name="name">
                <br><br>
                <div>
                    <label>Description:</label>
                    <textarea name="description"></textarea>
                </div>
                <br>
                <div>
                    <label>Members:</label>
                    <select name="members"></select>
                    <br><br>
                </div>
                <div>
                    <button type="sumbit">Create</button>
                </div>
            </form>
        </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h1>   {% for project in project_list %}
            {{ project.name }} </h1>
            <p> {{ project.description }} </p>
        {% endfor %}
            <h2>Tasks</h2>
            <p>
                <a href="http://localhost:8000/tasks/create.html"> Create a new task </a>
            </p>
            <div> {% for task in task %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Asignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td> {{ task.name }} </td>
                            <td> {{ tasks.assignee }} </td>
                            <td> {{ task.start_date|date:"m-d-Y" }}</td>
                            <td> {{ task.due_date|date:"m-d-Y" }}</td>
                            <td>  {{ task.is_completed  }}</td>
                        </tr>

            {% empty %}
                <p>This project has no tasks</p>
            {% endfor %}
            </div>
        </tbody>
    </table>
    </div>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h1>My Projects</h1>
        {% for project in project_list %}
        {% empty %}
            <div>
                <p>You are not assigned to any projects</p>
            </div>
        {% endfor %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
            </thead>
            <tbody>

                {% for project in project_list %}
                    <tr>
                        <td>{{ project.name }}</td>
                {% endfor %}

                {% for task in task_list %}
                    <td> {{ task.name }} </td>
                    </tr>
                {%  endfor  %}
            </tbody>
        </table>
        <br> <div>
            <a href="{% url 'create_project' %}">Create Project</a>
        </div>

    </div>
{% endblock content %}

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock content %}
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
            {% endif %}
        </main>
    </body>
</html>

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <br>
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            <div>
                <label>Name:</label>
                <input type="text" name="name">
                <br><br>
                <div>
                    <label>Start date:</label>
                    <input type="text" name="start_date">
                    <br><br>
                </div>
                <div>
                    <label>Due date:</label>
                    <input type="text" name="due_date">
                    <br><br>
                </div>
                <div>
                    <label>Project:</label>
                    <select name="projects"></select>
                    <br><br>
                </div>
                <div>
                    <label>Assignee:</label>
                    <select name="asignee"></select>
                    <br><br>
                </div>
                <button type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h1> My Tasks </h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Start date</th>
                    <th>End date</th>
                    <th>Is completed</th>
                </tr>
            </thead>
            <tbody>
                {% for task in task_list %}
                    <tr>
                        <td>{{ task.name }}</td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.end_date }}</td>
                        <td> {{ task.is_completed }}</td>
                    </tr>
                    <div>
                {% empty %}
                    <p>You have no tasks</p>
                    </div>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}